genkgo/camt

- src/DecoderInterface.php
- src/Reader.php
Camt053 Message type added to PHPDoc return value. 
When new types are supported, these can be added as well. 
Helps with type hinting in IDE's
> Added Message type Camt-53 to possible return value

- composer.json
- src/Camt054/Decoder/V04/Message.php
- src/DTO/Amount.php
- src/DTO/Charges.php
- src/DTO/ChargesRecord.php
- src/DTO/Entry.php
- src/DTO/EntryTransactionDetail.php
- src/DTO/GroupHeader.php
- src/DTO/RelatedDates.php
- src/Decoder/Entry.php
- src/Decoder/EntryTransactionDetail.php
- src/Decoder/Message.php
- src/Decoder/Record.php
- tests/Unit/Camt054/EndToEndTest.php
- tests/Unit/Camt054/Stubs/camt054.v2.xml
- tests/Unit/Decoder/EntryTest.php
- tests/Unit/Decoder/EntryTransactionDetailTest.php
Adding
```
$xmlDetail->Amt 
$xmlDetail->RltdDts->AccptncDtTm
$xmlDetail->Chrgs
$entry->Chrgs
```
This is my very first contribution on GitHub, so please bear with me ;-)
> Adding several Camt054.v4 Options

- composer.json
- src/Decoder.php
- test/Unit/Camt052/EndToEndTest.php
- test/Unit/Camt053/EndToEndTest.php
- test/Unit/Camt054/EndToEndTest.php
Money (https://github.com/moneyphp/money) is currently at v3. It's mostly compatible, except for the Currency api change. This upgrades to v3. Tests are passing.
> Update moneyphp to v3

- src/Decoder/Record.php
Besides `OPBD (OpeningBooked)`, `PRCD (PreviouslyClosedBooked)` is also used to indicate the opening balance. Moreover, explicitly check for `CLBD (ClosingBooked)` to avoid incorrectly marking unknown codes as closing balance (what happened to me with `PRCD`!).
Thank you!
Jarno
> Add opening balance code PRCD

- .travis.yml
- README.md
- composer.json
- src/Iban.php
- test/Unit/IbanTest.php
Stop receiving `Package jschaedl/iban is abandoned, you should avoid using it. Use jschaedl/iban-validation instead.`. ~~Because the new package requires PHP 7.1+, this project will also need to require PHP 7.1+.~~ Now use `globalcitizen/php-iban` 
Thanks in advance for merging!
Regards,
Jarno
> Stop using abandoned IBAN validator.

- src/DTO/CreditorReferenceInformation.php
- src/DTO/RemittanceInformation.php
- src/DTO/StructuredRemittanceInformation.php
- src/DTO/UnstructuredRemittanceInformation.php
- src/Decoder/EntryTransactionDetail.php
- test/Unit/Camt054/EndToEndTest.php
- test/Unit/Camt054/Stubs/camt054.v2.xml
- test/Unit/Camt054/Stubs/camt054.v4.xml
Regarding #58, ISR reference number can be lost if unstructured and structured blocks are present in a transaction details.
This feature don't break the compatibility and let the user decides to use the legacy `$transactionDetail->getRemittanceInformation()->getMessage();` method to retrieve remittance information or use the `StructuredRemittanceInformationand` and `UnstructuredRemittanceInformation ` new classes.
**ISR reference number**
`$transactionDetail->getRemittanceInformation()->getStructuredRemittanceInformation()->getCreditorReferenceInformation()->getRef()`
**Additional remittance information (usually the reject code in Switzerland)**
`$transactionDetail->getRemittanceInformation()->getStructuredRemittanceInformation()->getAdditionalRemittanceInformation()`
**Unstructured data …
> [CAMT.054] Complete remittance information with structured and unstructured blocks

- composer.json
- src/Iban.php
As discussed in https://github.com/genkgo/camt/pull/74. 
We moved to globalcitizen/php-iban because jschaedl/iban-validation required PHP 7.1. Because the next release is going to be PHP 7.2 we can move back to jschaedl/iban-validation.
Also added some return and parameter types.
>  Use jschaedl/iban-validation instead of globalcitizen/php-iban.

- test/Unit/Camt052/Decoder/MessageTest.php
- test/Unit/Camt053/Decoder/MessageTest.php
- test/Unit/Camt054/Decoder/MessageTest.php
- test/Unit/Decoder/EntryTest.php
- test/Unit/Decoder/RecordTest.php
- According to the [PHPUnit fixture reference](https://phpunit.readthedocs.io/en/8.5/fixtures.html?highlight=fixtures), the `setUp` method should be `protected`.
> Improve PHPUnit fixture methods

- src/DTO/BankTransactionCode.php
Because "BkTxCd" block has optionnal elements "Domn" and "Prtry", it must be allowed to return NULL.
XSD extract : 
https://github.com/genkgo/camt/blob/6391eed681f6f1e75fad4e720989bcc14e9da547/assets/camt.054.001.04.xsd#L156-L161
> BankTransactionCode must allow NULL Domain and Proprietary elements

- src/DTO/Charges.php
When parsing a CAMT.054 file, setTotalChargesAndTaxAmount is only called when a `Chrgs` record exists. Therefore, `getTotalChargesAndTaxAmount` must allow to return NULL
> Case with no charge

- .gitattributes
💁‍♂️ For reference, see https://git-scm.com/docs/gitattributes.
> Enhancement: Add `.gitattributes`

- src/Config.php
- test/Unit/ConfigTest.php
> Fix: Register all default message formats

- .php-cs-fixer.dist.php
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.4.0/doc/rules/language_construct/class_keyword_remove.rst.
> Fix: Do not configure deprecated `class_keyword_remove` fixer

- composer.json
- composer.lock
- phpstan.neon.dist
- test/Unit/Camt052/Decoder/MessageTest.php
- test/Unit/Camt053/Decoder/MessageTest.php
- test/Unit/Camt054/Decoder/MessageTest.php
- test/Unit/Decoder/EntryTest.php
- test/Unit/Decoder/EntryTransactionDetailTest.php
- test/Unit/Decoder/RecordTest.php
> Fix: Remove `phpspec/prophecy-phpunit`

- README.md
New standards 2022 are not supported by the library
https://www.six-group.com/dam/download/banking-services/interbank-clearing/de/standardization/consultation/sps-2022-high-level-information-de.pdf 
https://www.six-group.com/dam/download/banking-services/interbank-clearing/fr/standardization/consultation/sps-2022-high-level-information-fr.pdf
> Add new standard as not supported in Readme

- .php-cs-fixer.dist.php
💁‍♂️ Running
```shell
vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --diff --verbose
```
on current `master` yields
```
PHP CS Fixer 3.14.3 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.14
Loaded config default from ".php-cs-fixer.dist.php".
Using cache file "/var/folders/lz/j7s9n1kx4lnbpz098_wg6kbw0000gn/T/php-cs-fixer-Users-am-Sites-genkgo-camt".
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                                                                                                                                                                    106 / 106 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid …
```
> Enhancement: Enable `no_trailing_comma_in_singleline` fixer

- phpunit.xml
💁‍♂️ Running
```shell
vendor/bin/phpunit --configuration=phpunit.xml
```
on current `master` yields
```shell
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.14
Configuration: phpunit.xml
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
.............................................................     61 / 61 (100%)
Time: 00:00.129, Memory: 8.00 MB
OK (61 tests, 551 assertions)
```
> Fix: Migrate configuration for phpunit/phpunit

- .php-cs-fixer.dist.php
- test/Util/MoneyFactoryTest.php
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.14.0/doc/rules/php_unit/php_unit_data_provider_static.rst.
> Enhancement: Enable `php_unit_data_provider_static` fixer

- README.md
This change adds the version v11 as unsupported
version to the `README.md` file.
* camt.052.001.11
* camt.053.001.11
* camt.054.001.11
See: https://www.iso20022.org/iso-20022-message-definitions
> [DOCS] Document unsupported v11 version information

- src/DTO/Entry.php
- src/DTO/EntryTransactionDetail.php
- src/Decoder/Entry.php
- src/Decoder/EntryTransactionDetail.php
- src/Decoder/Record.php
- test/data/camt052.v1.json
- test/data/camt052.v2.json
- test/data/camt052.v2.other-account.json
- test/data/camt052.v4.json
- test/data/camt052.v6.json
- test/data/camt052.v8.json
- test/data/camt053.v2.five.decimals.json
- test/data/camt053.v2.minimal.json
- test/data/camt053.v2.minimal.ultimate.json
- test/data/camt053.v2.multi.statement.json
- test/data/camt053.v3.json
- test/data/camt053.v4.json
- test/data/camt053.v8.json
- test/data/camt054.v2.json
- test/data/camt054.v4.json
- test/data/camt054.v8-with-UETR.json
- test/data/camt054.v8-with-financial-institution.json
- test/data/camt054.v8.json
The credit-debit-identifier (CrdDbtInd) have been used for
several details, e.g. amount, to proper represent values.
The information itself is not added.
As it could not be reliable retrieved from subvalues what
the original state was, this change now adds that detail
directly to the transaction details and the entry itself.
Test fixture files are updated to contain the added fields.
Resolves: #146
Related: #116
> [FEATURE] Add `CreditDebitIdentifier` to entry transaction detail

- src/Camt054/Decoder/EntryTransactionDetail.php
- src/Decoder/EntryTransactionDetail.php
- test/Unit/RegressionTest.php
- test/data/camt054.v4.json
- test/data/camt054.v8.json
This fixes issue #83 for us, where at least in the camt.054.001.08 documents we receive the related agents' BIC are in BICFI nodes.
Test cases are also modified of course.
> fix(#83): RelatedAgents' BIC may be in BICFI instead of BIC node

- .github/workflows/main.yml
- composer.json
- composer.lock
This pull request includes a small change to the `.github/workflows/main.yml` file. The change adds support for PHP version 8.4 to the CI workflow.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R12): Added PHP version 8.4 to the matrix of versions to test in the CI workflow.
It might very well be that when the pipeline is executed some deprecations might pop up. If any show up I am willing to spend some additional time in getting them resolved.
> Add PHP 8.4 to build matrix

- src/Camt052/Decoder/EntryTransactionDetail.php
- src/Camt052/Decoder/Message.php
- src/Camt053/Decoder/EntryTransactionDetail.php
- src/Camt053/Decoder/Message.php
- src/Camt054/Decoder/EntryTransactionDetail.php
- src/Camt054/Decoder/Message.php
- src/DTO/IbanAccount.php
- test/data/camt052.v2.json
- test/data/camt052.v2.with-account-name.json
- test/data/camt052.v2.with-account-name.xml
- test/data/camt052.v4.json
- test/data/camt052.v6.json
- test/data/camt053.v2.all-balance-types.json
- test/data/camt053.v2.five.decimals.json
- test/data/camt053.v2.minimal.json
- test/data/camt053.v2.minimal.ultimate.json
- test/data/camt053.v2.multi.statement.json
- test/data/camt053.v2.with-account-name.json
- test/data/camt053.v2.with-account-name.xml
- test/data/camt053.v3.json
- test/data/camt053.v4.json
- test/data/camt053.v8.json
- test/data/camt054.v2.with-account-name.json
- test/data/camt054.v2.with-account-name.xml
- test/data/camt054.v4.json
- test/data/camt054.v8-with-financial-institution.json
- test/data/camt054.v8.json
`IbanAccount::getName()` return the account name if defined in the CAMT file.
Closes #161
> Add support for named iban accounts

- src/DTO/Creditor.php
- src/DTO/Debtor.php
- src/DTO/PrivateIdentification.php
- src/DTO/RelatedPartyTypeInterface.php
- src/Decoder/EntryTransactionDetail.php
- src/Decoder/Factory/DTO/PrivateIdentification.php
- test/Unit/Camt053/EndToEndTest.php
- test/data/camt052.v2.other-account.json
- test/data/camt052.v2.with-account-name.json
- test/data/camt052.v4.json
- test/data/camt052.v6.json
- test/data/camt053.v2.all-balance-types.json
- test/data/camt053.v2.five.decimals.json
- test/data/camt053.v2.minimal.json
- test/data/camt053.v2.minimal.ultimate.json
- test/data/camt053.v2.multi.statement.json
- test/data/camt053.v2.with-account-name.json
- test/data/camt053.v2.with-party-ids.json
- test/data/camt053.v2.with-party-ids.xml
- test/data/camt053.v3.json
- test/data/camt053.v4.json
- test/data/camt053.v8.json
- test/data/camt054.v2.json
- test/data/camt054.v2.with-account-name.json
- test/data/camt054.v4.json
- test/data/camt054.v8-with-financial-institution.json
- test/data/camt054.v8.json
This PR resolves issue #167 and partly covers PR #141 
The Id structure used in Related parties is extended to include Private Identification or Organisation Identification. This structure is reused in many parts of the CAMT (and PAIN) but for now implemented in related parties. It could probably be reused in other parts.
> Add support for Related party identification structure

- src/Decoder/EntryTransactionDetail.php
- src/Decoder/Record.php
- test/Unit/RegressionTest.php
- test/data/camt052.v6.Amt-zero.json
- test/data/camt052.v6.Amt-zero.xml
> Don't check for truthy amount values when creating ChargesRecord objects
